import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles(theme => ({
  wrapper: (props: any) => ({
    display: "block",
    margin: props.margin,
  }),
  button: {
    borderColor: "white",
    height: "50px",
    outline: "none",
    border: "none",
    display: "flex",
    alignItems: "center",
    fontSize: "13px",
    letterSpacing: "2px",
    padding: "0 15px",
    position: "relative",
    cursor: "pointer",
    fontWeight: "bold",
    textTransform: "uppercase",
    transition: "all 0.3s ease-in-out",
    "&:hover": {
      color: "#767677",
      transition: "all 0.3s ease-in-out",
    },
  },
  buttonLight: {
    backgroundColor: "white",
    borderColor: "white",
    color: "black",
    "&::before": {
      content: '""',
      width: "100%",
      bottom: "-3px",
      position: "absolute",
      borderBottom: "1px solid white",
      borderLeft: "1px solid white",
      left: "3px",
      height: "3px",
      boxSizing: "border-box",
    },
    "&::after": {
      content: '""',
      width: "3px",
      position: "absolute",
      borderRight: "1px solid white",
      borderTop: "1px solid white",
      height: "100%",
      right: "-3px",
      top: "3px",
      boxSizing: "border-box",
    },
  },
  buttonDark: {
    backgroundColor: "black",
    color: "white",
    borderColor: "black",
    "&::before": {
      content: '""',
      width: "100%",
      bottom: "-3px",
      position: "absolute",
      borderBottom: "1px solid black",
      borderLeft: "1px solid black",
      left: "3px",
      height: "3px",
      boxSizing: "border-box",
    },
    "&::after": {
      content: '""',
      width: "3px",
      position: "absolute",
      borderRight: "1px solid black",
      borderTop: "1px solid black",
      height: "100%",
      right: "-3px",
      top: "3px",
      boxSizing: "border-box",
    },
  },
}));

export default useStyles;
